### ISSUE TITLE
Explore the use of using a third party emoji library

### ISSUE THREAD

**Issue by BrianMitchL** [BrianMitchL/heygetbacktowork#14]
This would allow Linux and older clients to view emoji. It would also ensure that emoji appear or look the same on all platforms. This could also just be used on systems with no provided emoji library.

**Comment by card100** [comment]
I would recommend https://afeld.github.io/emoji-css/.
It's the same across browsers on all systems.

**Comment by BrianMitchL** [comment]
Perfect, that looks great, thanks for the suggestion!
